### ISSUE TITLE
TODO React 1

### ISSUE THREAD

**Issue by Relacibo** [Relacibo/p2p-chessvariants#1]
- [x] Sidebar
  - [x] ~~Image (create new one for vertical format)~~
  - [x] Size
  - [x] Sidebar Hide when starting game, full in main menu
- [ ] Game start options
- [ ] Game list
- [ ] Variants collection
  - [ ] Everyone can add custom url as variant description (sanitize)
  - [ ] Have option to show code 
  - [ ] Everyone can update variant description (sanitize)
  - [ ] Have a list with recommended urls
      - [ ] list should have hash of script for validation.
- [ ] Lobby/Host game controls
  - [ ] Host can move positions of players (for now) (sanitize)
  - [ ] People can join hosts by hostid or gameid
  - [ ] Host can invite players to lobby
- [ ] chessboard
  - [ ] Board
  - [ ] Pieces
  - [ ] Move
  - [ ] Premove
  - [ ] Promote
  - [ ] Reserve Pile
  - [ ] At some point clock
  - [ ] Some sort of display for the mod (maybe with md)
