### ISSUE TITLE
TODO Worker / defaults / VariantDescription 1

### ISSUE THREAD

**Issue by Relacibo** [Relacibo/p2p-chessvariants#2]
- [x] uuids as key
- [x] indexeddb instead of localstorage
- [x] typing of context
- [ ] Add some additional hooks like useRandom
- [ ] Every instance validates move. Every instance uses same random values.
- [ ] cache possibleDestinations
- [ ] replace Description if it has same uuid
- [ ] Validate description
- [ ] #3
