### ISSUE TITLE
TODO: PeerJS 1

### ISSUE THREAD

**Issue by Relacibo** [Relacibo/p2p-chessvariants#5]
- [x] Replace peerId with uuid
- [ ] Create Message queue for sending
- [ ] (Maybe Message queue for receiving)
- [ ] Handle disconnection/reconnection
- [ ] Maybe support manual reconnecting with id
- [ ] Handle Reloading of page
- [ ] Create Lobby
- [ ] Join Lobby
- [ ] Some protocol
